spring.datasource.url=jdbc:mysql://localhost:3306/PASTEL_DB
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect