spring.datasource.url=jdbc:mysql://localhost:3306/PASTEL_DB
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

app.base-url=${APP_BASE_URL:http://localhost:8080}

mercadopago.public-key=${MERCADO_PAGO_PUBLIC_KEY:APP_USR-d1510e2d-52ea-447b-90c4-dc9dabf69d97}
mercadopago.access-token=${MERCADO_PAGO_ACCESS_TOKEN:APP_USR-91433170228563-062315-1358f49a5835e09c9b7beee94f92bc9a-3494674816}
mercadopago.use-sandbox-init-point=${MERCADO_PAGO_USE_SANDBOX_INIT_POINT:true}
